### PR TITLE
feat (slot): add slot controller

### LINKED ISSUE #10: Suggested controller: SlotController
Within the community, various teams already have some form of a slot controller to basically abstract the slotchanged/assigned elements logic.

It'd probably be a good idea for us to provide such a controller. It could also act as a base to other slot-based controllers.

basically:

```ts
class SlotController implements ReactiveController {
  constructor(
    host: ReactiveControllerHost,
    slotRef: Ref,
    selector?: string
  );
}
```

how we pass in a change handler, im not sure yet.

could be a constructor arg, or a method, etc.

### PR DESCRIPTION
**Pull request by 43081j**
The slot controller allows you to observe slotted elements:

```ts
const ctrl = new SlotController(host);

// elsewhere...

html`
  <slot ${ref(ctrl.ref)}></slot>
`;
```

We can then listen for particular elements being slotted:

```ts
ctrl.addListener((divNode) => {
  // divNode is always a `<div>` here thanks to the selector
}, {selector: 'div'});
```

Fixes #10 

cc @e111077 if you wanna take a look, this is what we mentioned on discord

### CODE REVIEW

**Comment by e111077** [comment]
Why doesn't the controller generate the ref instead of passing one in? it's all Lit, so can we assume it uses a Lit ref?

Additionally, not too sure what the benefit is, can you provide a cool use case where this reduces boilerplate over a `@slotchange`?

Finally, can it provide a "deep" functionality. Often I have

```html
<my-el>
  <div>asdf</div>
  <a><div>qwerty</div></a>
</my-el>
```

And I want both DIVs

**Comment by 43081j** [comment]
@e111077 ah i get you, as in just `createRef` internally and do something like this:

```ts
html`
  <slot ${ref(this._slotCtrl.ref)}></slot>
`;
```

that would be nice.

we could easily traverse children rather than only directly slotted ones too i think. just some tree walker maybe?

as for how useful this is - for a basic slot change handler, not very. i think in its current state, the selector logic is what is useful more than the listener.

i was trying to think of a way to extend this too, to somehow auto propagate props/attrs to slotted nodes. but nothing came to me yet.

**Comment by 43081j** [comment]
i've updated at least to:

- auto create a ref
- rework the listener to have options so it can be extended in future

meanwhile ill see if i can add a `options.deep` option of some sort

**Comment by 43081j** [comment]
@e111077 

```ts
ctrl.addListener((node) => {

}, {
  selector: 'span',
  deep: true
});
```

With this DOM:

```html
<host-element>
  <div>
    <span>Foo</span>
  </div>
  <span>Bar</span>
</host-element>
```

would result in your listener being called for each span.

however, it is still based purely on slot changes. so ofc if you add the `span` later without changing the slotted elements, your listener won't be called (would need a mutation observer there).

is that what you had in mind?

**Comment by e111077** [comment]
> it is still based purely on slot changes

hmm that's a good point. I say shelve the `deep` idea for now, but yeah that's what I had in mind

**Comment by e111077** [comment]
Another idea, should `addListener` mimic `addEventListener`?

`ctrl.addListener(selector, callback, options?)` Or do you think it should be just an object? `ctrl.addListener({selector, callback, queryAll: false})`

**Comment by e111077** [comment]
Finally, should the callback be an `Array` or basically a `forEach` call? I think the argument for array is that you might have a thing like a list that needs to see what is previous and what is next. The argument against it is, why not just do a `<slot @slotchange=${...}>` + `@queryAssignedElements({selector: 'div'}) assignedDivs!: HTMLDivElement[]`?

**Comment by 43081j** [comment]
> hmm that's a good point. I say shelve the `deep` idea for now, but yeah that's what I had in mind

i think i agree, since we could solve it with some sort of mutation observer controller in future possibly.

> Another idea, should `addListener` mimic `addEventListener`?
> 
> `ctrl.addListener(selector, callback, options?)` Or do you think it should be just an object? `ctrl.addListener({selector, callback, queryAll: false})`. The latter might make it harder to eventually add a `removeListener`

originally i wanted `addListener(selector, callback)` but wasn't sure if there was some chance in future we listen based on some other thing. maybe thinking too far ahead though.

i also wanted to avoid overloads like `addListener(callback)` and `addListener(selector, callback)` since it just makes the implementation messy (and the type inference).

we could just require that if you want to match _all_ elements, you pass `'*'`. rather than having a separate overload without a selector.

> Finally, should the callback be an `Array` or basically a `forEach` call a you currently have it? I think the argument for array is that you might have a thing like a list that needs to see what is previous and what is next. The argument against it is, why not just do a `<slot @slotchange=${...}>` + `@queryAssignedElements({selector: 'div'}) assignedDivs!: HTMLDivElement[]`?
> 

i think in both cases its near enough equal to using a slotchange handler and the query decorator.

however, its possible we could extend this controller to do things like this too:

```ts
ctrl.bindAttributes({
  'selected': (node, idx) => this.selectedIndex === idx,
  'tabindex': '-1'
});
```

by itself, its seeming less of a benefit the more i think about it (over a decorator/listener). but if there's some useful methods along these lines, it'd be of more use.

> Sorry for all the philosophical questions without much code review, I just want to get this design right.

don't worry about it, all of this is super helpful. definitely appreciate having some of your time

**Comment by e111077** [comment]
I think we need to prove out that this controller can be composed with other controllers. Like a `BindToSlotted` controller that just composes this slot controller and a possible bind controller?

I think that's where the real benefit of this controller lies – it packages slotchange + queryAssignedElements into a sharable primitive for other controllers to consume.

**Comment by 43081j** [comment]
I agree

The controller to bind attributes/properties to slotted children could build on top of this. With a similar interface to what I mentioned unless we think of a better one. 

I'll have a play around with it this weekend

**Pull request merged**
